# Generated by Django 5.1.7 on 2025-04-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='user',
        ),
    ]
