# Generated by Django 5.1.7 on 2025-04-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_level_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='website.language')),
            ],
        ),
        migrations.CreateModel(
            name='TabooWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taboo_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_taboo_word', to='website.word')),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taboo_for', to='website.word')),
            ],
        ),
    ]
