# Generated by Django 5.1.7 on 2025-04-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_tabooset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabooCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taboo_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='website.tabooset')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taboo_cards', to='website.word')),
            ],
        ),
        migrations.CreateModel(
            name='TabooCardTabooWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taboo_links', to='website.taboocard')),
                ('taboo_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_taboo', to='website.word')),
            ],
            options={
                'unique_together': {('card', 'taboo_word')},
            },
        ),
    ]
