# Generated by Django 5.1.7 on 2025-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_timelog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
