# Generated by Django 5.1.7 on 2025-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_taboocard_taboocardtabooword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'language')},
        ),
    ]
