# Generated by Django 5.1.7 on 2025-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_prompt_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='level',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
