# Generated by Django 5.1.7 on 2025-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_prompt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
