# Generated by Django 5.1.7 on 2025-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_prompt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
