name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "DJANGO_SECRET_KEY=testing" >> $GITHUB_ENV
          echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_postgres" >> $GITHUB_ENV
          echo "DB_SSL=false" >> $GITHUB_ENV

      - name: Run migrations and tests
        env:
          DJANGO_SETTINGS_MODULE: LargeEnglish.settings
        run: |
          python manage.py migrate
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # ✅ only run this if tests pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/large-english/le

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy le \
            --image gcr.io/large-english/le \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --set-env-vars DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --set-env-vars STORAGE_ROOT_URL=${{ secrets.STORAGE_ROOT_URL }} \
            --set-env-vars SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --set-env-vars DEBUG=False
